### ISSUE TITLE
suggestion: advertising clean up

### ISSUE THREAD

**Issue by spfeifer222** [federicocalendino/pysub-parser#2]
Dear Federico,

how about removing advertising subtitles by defining a regex ADVERTISING_CLEANER pattern:

```
ADVERTING_CLEANER = re.compile(r'''
                    .*?    # non-greedy match before adv
                    (www\.Addic7ed\.com|corrected by) # adv keywords
                    .*     # rest of the subtitle
                    ''', re.UNICODE|re.VERBOSE|re.IGNORECASE|re.DOTALL)
```
and add 

```
if remove_advertising:
            text = ADVERTING_CLEANER.sub('', text)
```
to the `clean_up` method?

It's not the most elegant solution, because empty subtitles are left, but it works.

**Comment by fedecalendino** [comment]
Hi @spfeifer222! I really forgot about this repo. 
Would you have a few subtitles with advertisements so I can try your regex out?

Thanks for the suggestion! :)
