### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 3: invalid start byte

### ISSUE THREAD

**Issue by anbo724** [federicocalendino/pysub-parser#4]
Hi, when I use this package to parse the sub files from shooter subtitles, I found a problem.
`from pysubparser import parser

if __name__ == '__main__':
	subtitles = parser.parse('/home/aa/subtitle/3/Thirteen.Days.CD2-TheFrail.sub')
	for subtitle in subtitles:
		print(subtitle)`

raceback (most recent call last):
  File "/home/aa/mycode/data_process/home/anbo/mycode/data_process/paraphrase_data/subtitles.py", line 5, in <module>
    for subtitle in subtitles:
  File "/home/aa/anaconda3/envs/knlu/lib/python3.6/site-packages/pysubparser/parsers/sub.py", line 33, in parse
    for line in file:
  File "/home/aa/anaconda3/envs/knlu/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 3: invalid start byte

**Comment by fedecalendino** [comment]
Hi @anbo724!

It seems that the file that you are trying to read isn't encoded with `utf-8`. 

When calling to `parser.parse` you can also indicate an optional encoding like so:

```python
    subtitles = parser.parse('/home/aa/subtitle/3/Thirteen.Days.CD2-TheFrail.sub', encoding="utf-8")
    
    for subtitle in subtitles:
        print(subtitle)
```

and you can replace `utf-8` for any other encoding that might suit your file.


You can also change the encoding of your file with a text editor before using the parser.


Let me know how it goes!

**Comment by swahareddy** [comment]
@anbo724 , you can try this
```
from bs4 import UnicodeDammit
def get_encoding(subtitle_path):
    with open(subtitle_path, 'rb') as file:
       content = file.read()

    suggestion = UnicodeDammit(content)
    return(suggestion.original_encoding)
```
And then 
    ```subtitles = parser.parse(subtitle_path, encoding=get_encoding(subtitle_path))```

**Comment by danon** [comment]
@fedecalendino Hi! Cool library, really useful.

Could you write in `ReadMe.md` the list of available/supported encodings?
