### ISSUE TITLE
"\n" Support

### ISSUE THREAD

**Issue by jetley** [federicocalendino/pysub-parser#5]
Hi, I love using this project for my library. It's got everything I need, but there's a minor inconvenience other libraries doesn't have (as far as I know); **does this library print "\n"**? If it does, how? And if it doesn't, can it be implemented? Thanks in advance.

**Comment by fedecalendino** [comment]
do you mean having a \n when a subtitle instance has two or more lines?

**Comment by jetley** [comment]
Yes

**Comment by fedecalendino** [comment]
The `text` methods is intended to give everything in one line.

If you need each lines of a subtitle, and then make the output that you need you can get them via the `Subtitle.lines` attributes.

```python
from pysubparser.classes.subtitle import Subtitle

def custom_printer(subtitle):
    print("\n".join(subtitle.lines))

sub = Subtitle(0, lines=["First line", "Second line"])

print(sub.text)
>>> First line Second line

print(sub.lines)
>>> ['First line', 'Second line']

custom_printer(sub)
>>> First line
Second line
```
